// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmk85KFES3lxFulEkvYLOKQF-_bJ59vT4',
    appId: '1:449605742474:web:e90cd25b71108c77b06273',
    messagingSenderId: '449605742474',
    projectId: 'workdone-15c4a',
    authDomain: 'workdone-15c4a.firebaseapp.com',
    storageBucket: 'workdone-15c4a.appspot.com',
    measurementId: 'G-231WSS7QKZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO53vuIX34pqqU-H2I0TaoISOY_qvbuQQ',
    appId: '1:449605742474:android:ff1dc39813c79a08b06273',
    messagingSenderId: '449605742474',
    projectId: 'workdone-15c4a',
    storageBucket: 'workdone-15c4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNDMULqPAqn2uMyfYU1HYd4Evbk4puz2U',
    appId: '1:449605742474:ios:05851cd039597312b06273',
    messagingSenderId: '449605742474',
    projectId: 'workdone-15c4a',
    storageBucket: 'workdone-15c4a.appspot.com',
    iosBundleId: 'com.example.workdone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNDMULqPAqn2uMyfYU1HYd4Evbk4puz2U',
    appId: '1:449605742474:ios:a23026a909003dc9b06273',
    messagingSenderId: '449605742474',
    projectId: 'workdone-15c4a',
    storageBucket: 'workdone-15c4a.appspot.com',
    iosBundleId: 'com.example.workdone.RunnerTests',
  );
}
