# Uncomment this line to define a global platform for your project
platform :ios, '11.0'

target 'Runner' do
 use_frameworks! # Add this line if it's not already present

 # Pods for Runner
 # Add your pods here
 pod 'SomeDependency', '~> 1.0.0'

 # Correct usage of use_modular_headers!
 use_modular_headers!

 # Configuring iOS settings for Runner target
 # Remove or comment out the following lines
 # config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'NO'
 # config.build_settings['CLANG_WARN_OBJC_LITERAL_CONVERSION'] = 'YES'
 # config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'

 # Post-install script to ensure compatibility across all pods
 post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end
    end
 end
end
